### ISSUE TITLE
Bower install (use ember install instead of npm install)

### ISSUE THREAD

**Issue by joostdevries** [joostdevries/twiddle-backend#1]
```
Error: ENOENT, no such file or directory '/tmp/build-ember-cli-selectize-0-5-2-ember-1-13-15/tmp/concat_with_maps-input_base_path-V9elLVbJ.tmp/0/bower_components/selectize/dist/js/standalone/selectize.js' 
 at Object.fs.openSync (fs.js:439:18) 
 at Object.fs.readFileSync (fs.js:290:15) 
 at SourceMap.addFile (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:69:31) 
 at /var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat.js:96:14 
 at Array.forEach (native) 
 at ConcatWithMaps.build (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat.js:94:22) 
 at /var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:152:21 
 at lib$rsvp$$internal$$tryCatch (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16) 
 at lib$rsvp$$internal$$invokeCallback (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17) 
 at lib$rsvp$$internal$$publish (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11) 
2016-03-10T17:00:59.136Z    9e58fc73-e6e1-11e5-8993-99dc33446a30    Replacing app name... 
2016-03-10T17:00:59.136Z    9e58fc73-e6e1-11e5-8993-99dc33446a30    Error: { [Error: ENOENT, open '/tmp/ember-cli-selectize-0-5-2-ember-1-13-15/addons.js'] errno: 34, code: 'ENOENT', path: '/tmp/ember-cli-selectize-0-5-2-ember-1-13-15/addons.js' } 
```

**Comment by joostdevries** [comment]
Fixable by running ember install instead of npm install... Will have to test what that does in terms of time though..
